### ISSUE TITLE
midpoint rooting fails

### ISSUE THREAD

**Issue by mmolari** [PierreBarrat/TreeTools.jl#41]
Hello!
I have a simple example where midpoint rooting fails. The tree ([tree.zip](https://github.com/PierreBarrat/TreeTools.jl/files/12408225/tree.zip)) looks as follows:
![image](https://github.com/PierreBarrat/TreeTools.jl/assets/18715871/8831646c-dd90-4f67-ab93-3eb469f1200a)

When running:
```
using TreeTools

tree = open("tree.nwk", "r") do io
    str = read(io, String)
    # strip newline
    str = str[1:end-1]
    TreeTools.parse_newick_string(str)
end

TreeTools.root!(tree; method = :midpoint)
```

I get the following error:
```
ERROR: TypeError: non-boolean (Missing) used in boolean context
Stacktrace:
 [1] find_midpoint(t::Tree{TreeTools.EmptyData}; topological::Bool)
   @ TreeTools ~/ownCloud/neherlab/code/treetools_debug/TreeTools/src/methods.jl:721
 [2] root_midpoint!(t::Tree{TreeTools.EmptyData}; topological::Bool)
   @ TreeTools ~/ownCloud/neherlab/code/treetools_debug/TreeTools/src/methods.jl:625
 [3] #root!#32
   @ ~/ownCloud/neherlab/code/treetools_debug/TreeTools/src/methods.jl:611 [inlined]
 [4] top-level scope
   @ ~/ownCloud/neherlab/code/treetools_debug/test.jl:13
```

I looked a bit into it and it looks like a numerical approximation error. It seems that in [this loop](https://github.com/PierreBarrat/TreeTools.jl/blob/f88e3b42f9995754c7ff996046c8824e72ad3ecf/src/methods.jl#L721), while climbing up the tree, the leading node reaches the root. the value of `d` becomes approximately equal to `max_dist/2` (`0.005130294` vs ` 0.0051302940000000005`) but this triggers another iteration, trying to get the ancestor of the root and generating the failure.

The error might be corrected by relaxing the previous condition and terminating the iteration also when the two values are approximately equal, see for instance [this line](https://github.com/PierreBarrat/TreeTools.jl/blob/f88e3b42f9995754c7ff996046c8824e72ad3ecf/src/methods.jl#L711).
Or alternatively (and maybe more elegantly) the iteration could also be stopped if the root node is reached.

Ciao!
Marco

**Comment by PierreBarrat** [comment]
Ciao Marco! 
PR above should have fixed it. Can you try and tell me if it works? (I merged it already anyway). 
Indeed the problem occurred when the midpoint is exactly on the current root ... 

By the way, you can use `tree = read_tree("tree.nwk")` to read the tree.
