### ISSUE TITLE
Display faills when node has a singular child

### ISSUE THREAD

**Issue by mushunrek** [PierreBarrat/TreeTools.jl#43]
The following code fails:
```
tree = Tree()
graft!(tree, TreeNode(label="A"), tree[""], graft_on_leaf=true)
tree
```
The problem seems to be that the visualization assumes to have at least two children and wants to draw vertical lines. If this is not the case, an out of bounds error is thrown.

**Comment by PierreBarrat** [comment]
Should be fixed with above PR. 
I'll update the minor version later today.
